# Generated by Django 3.2.17 on 2023-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lang',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
