# Generated by Django 3.2.17 on 2023-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restorent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lang',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
