# Generated by Django 4.1.4 on 2023-01-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
