# Generated by Django 3.2.17 on 2023-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('SA', 'SuperAdmin'), ('AD', 'Admin'), ('US', 'User')], default='US', max_length=2),
        ),
    ]
