# Generated by Django 3.2.17 on 2023-02-10 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restorent_password'),
        ('users', '0003_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('type', models.CharField(choices=[('SA', 'SuperAdmin'), ('AD', 'Admin')], default='AD', max_length=2)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_name', to='restaurants.restaurant')),
            ],
        ),
    ]
