# Generated by Django 3.2.17 on 2023-03-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20230310_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
