# Generated by Django 3.2.17 on 2023-03-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_alter_quantity_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together={('title', 'item')},
        ),
    ]
