# Generated by Django 3.2.17 on 2023-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_quantity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
